OP_0 = "0"
OP_1 = "1"
OP_2 = "2"
OP_3 = "3"
OP_4 = "4"
OP_5 = "5"
OP_6 = "6"
OP_7 = "7"
OP_8 = "8"
OP_9 = "9"
OP_10 = "a"
OP_11 = "b"
OP_12 = "c"
OP_13 = "d"
OP_14 = "e"
OP_15 = "f"
OP_16 = "x"
OP_NOP = " = "
OP_NOP2 = "\n"
OP_ADD = "+"
OP_ADD_10 = "g"
OP_ADD_20 = "h"
OP_ADD_30 = "i"
OP_ADD_40 = "j"
OP_ADD_50 = "k"
OP_ADD_60 = "l"
OP_ADD_70 = "m"
OP_ADD_80 = "n"
OP_SUB = "-"
OP_MUL = "*"
OP_DIV = "/"
OP_NEGATE = "_"
OP_AND = "&"
OP_OR = "|"
OP_NOT = "~"
OP_LESSTHAN = "<"
OP_GREATERTHAN = ">"
OP_EQUAL = "="
OP_DUP = "$"
OP_TUCK = "T"
OP_2DUP = "D"
OP_3DUP = "C"
OP_DROP = "%"
OP_SWAP = "\\"
OP_ROT = "@"
OP_PICK = "O"
OP_JMP = "J"
OP_JZ = "Z"
OP_JNZ = "N"
OP_RETURN = "R"

def print_result(prog)
  result = prog.join('')
  puts "code: " + result
  puts "XML : " + result.gsub(/</, '&lt;')
  print "C   : "
  p result
end
